FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y curl;
RUN curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh && sh nodesource_setup.sh && apt-get update && apt-get install -y build-essential ruby-dev nodejs;
RUN gem install compass;

VOLUME /log

# Create app directory
WORKDIR /usr/src/cards

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied where available (npm@5+)
COPY app/package*.json ./

RUN npm install
RUN npm install -g nodemon;

# Bundle app source
COPY . .

EXPOSE 3001

ARG git_hash
ENV env_hash=dev

ARG git_date
ENV env_date=dev

RUN export NODE_ENV=development

RUN compass compile /usr/src/cards/app;

ADD entrypoint.sh /bin/entrypoint.sh
RUN chmod a+rwx /bin/entrypoint.sh
ENTRYPOINT ["/bin/entrypoint.sh"]
