FROM node:10

VOLUME /log

# Create app directory
WORKDIR /usr/src/cards

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY app/package*.json ./

RUN npm install
RUN npm install -g nodemon;

# Bundle app source
COPY . .

EXPOSE 3001

ARG git_hash
ENV env_hash=dev

ARG git_date
ENV env_date=dev

# ENTRYPOINT
ADD entrypoint.sh /bin/entrypoint.sh
RUN chmod a+rwx /bin/entrypoint.sh
ENTRYPOINT ["/bin/entrypoint.sh"]