version: '2'
services:
  cards-node:
    build:
      context: '.'
      dockerfile: 'Dockerfile-compose'
    hostname: 'cards-node'
    container_name: 'cards-node'
    working_dir: '/usr/src/cards'
    tty: true
    ports:
      - '3001:3001'
    volumes:
      - './app:/usr/src/cards'
      - 'cards-node-data:/log'
    links:
      - 'cards-redis:redis'
    networks:
      - app
      
  cards-redis:
    ports:
      - 6379
    image: 'redis:3'
    volumes:
      - 'cards-redis-data:/data'
    container_name: 'cards-redis'
    hostname: 'cards-redis'
    networks:
      - 'app'
      
volumes:
  cards-node-data:
  cards-redis-data:

networks:
  app:
    driver: bridge
